import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, Pencil, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api, formatMoney } from '../lib/api';

type Fund = { id: string; actividad: 'PRODUCTOS' | 'PRESTAMOS'; saldo_actual: string };
type Partner = { id: string; nombre: string; activo: boolean; custodias: Fund[] };

export function PartnersPage() {
  const [partners, setPartners] = useState<Partner[]>([]); const [editing, setEditing] = useState<Partner | null>(null); const [name, setName] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  async function load() { setPartners((await api<{ data: Partner[] }>('/catalogo/socios')).data); }
  useEffect(() => { void load().catch((error) => setMessage(error instanceof Error ? error.message : 'No se pudieron cargar los socios.')); }, []);
  async function save(event: FormEvent) { event.preventDefault(); if (!editing) return; setSaving(true); setMessage(''); try { await api(`/catalogo/socios/${editing.id}`, { method: 'PATCH', body: JSON.stringify({ nombre: name }) }); await load(); setEditing(null); setName(''); setMessage('Nombre del socio actualizado sin cambiar sus relaciones.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo actualizar el socio.'); } finally { setSaving(false); } }
  return <><section className="page-title"><div><p className="eyebrow">CONFIGURACIÓN</p><h2>Socios</h2><p>Edita únicamente el nombre asociado al mismo identificador.</p></div><Link className="secondary" to="/configuracion"><ArrowLeft size={17} /> Volver</Link></section><div className="admin-layout"><section className="panel"><div className="panel-head"><div><h3>Editar socio</h3><p>Sus fondos, préstamos y operaciones permanecen asociados al mismo UUID.</p></div></div>{editing ? <form className="compact-form admin-form" onSubmit={save}><label>Nombre<input required minLength={2} maxLength={120} value={name} onChange={(event) => setName(event.target.value)} /></label><div className="form-actions"><button type="button" className="secondary" onClick={() => setEditing(null)}>Cancelar</button><button className="primary" disabled={saving}>{saving ? 'Guardando…' : 'Guardar nombre'}</button></div></form> : <div className="empty-state">Selecciona Editar junto al socio que deseas actualizar.</div>}{message && <p className="form-message admin-message">{message}</p>}</section><section className="panel list-panel"><div className="table-tools"><strong>Socios existentes</strong><span>{partners.length} registros</span></div><div className="table-wrap"><table><thead><tr><th>Nombre</th><th>Fondos asociados</th><th>Acciones</th></tr></thead><tbody>{partners.length ? partners.map((partner) => <tr key={partner.id}><td>{partner.nombre}</td><td><div className="partner-funds">{partner.custodias.map((fund) => <span key={fund.id}><WalletCards size={13} /> {fund.actividad} · {formatMoney(fund.saldo_actual)}</span>)}</div></td><td><button className="edit-button" onClick={() => { setEditing(partner); setName(partner.nombre); setMessage(''); }}><Pencil size={14} /> Editar</button></td></tr>) : <tr><td colSpan={3} className="empty-cell">No hay socios registrados.</td></tr>}</tbody></table></div></section></div></>;
}
