import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, Pencil, Plus, Power } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';

type Provider = { id: string; nombre: string; identificacion: string | null; telefono: string | null; direccion: string | null; activo: boolean };
const empty = { nombre: '', identificacion: '', telefono: '', direccion: '' };

export function ProvidersPage() {
  const [providers, setProviders] = useState<Provider[]>([]); const [editing, setEditing] = useState<Provider | null>(null); const [form, setForm] = useState(empty); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  async function load() { setProviders((await api<{ data: Provider[] }>('/catalogo/proveedores')).data); }
  useEffect(() => { void load().catch((error) => setMessage(error instanceof Error ? error.message : 'No se pudieron cargar los proveedores.')); }, []);
  function startNew() { setEditing(null); setForm(empty); setMessage(''); }
  function startEdit(provider: Provider) { setEditing(provider); setForm({ nombre: provider.nombre, identificacion: provider.identificacion ?? '', telefono: provider.telefono ?? '', direccion: provider.direccion ?? '' }); setMessage(''); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(''); try { const body = { nombre: form.nombre, identificacion: form.identificacion || null, telefono: form.telefono || null, direccion: form.direccion || null }; await api(`/catalogo/proveedores${editing ? `/${editing.id}` : ''}`, { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(body) }); startNew(); await load(); setMessage('Proveedor guardado correctamente.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo guardar el proveedor.'); } finally { setSaving(false); } }
  async function toggle(provider: Provider) { setSaving(true); setMessage(''); try { await api(`/catalogo/proveedores/${provider.id}`, { method: 'PATCH', body: JSON.stringify({ activo: !provider.activo }) }); await load(); setMessage(`Proveedor ${provider.activo ? 'desactivado' : 'activado'} correctamente.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo cambiar el estado.'); } finally { setSaving(false); } }
  return <><section className="page-title"><div><p className="eyebrow">CONFIGURACIÓN</p><h2>Proveedores</h2><p>Administra los datos de compra sin eliminar su historial.</p></div><Link className="secondary" to="/configuracion"><ArrowLeft size={17} /> Volver</Link></section><div className="admin-layout"><section className="panel"><div className="panel-head"><div><h3>{editing ? 'Editar proveedor' : 'Nuevo proveedor'}</h3><p>Los proveedores inactivos conservan todas sus compras.</p></div>{editing && <button className="secondary" type="button" onClick={startNew}><Plus size={15} /> Nuevo</button>}</div><form className="compact-form admin-form" onSubmit={save}><label>Nombre<input required minLength={1} maxLength={180} value={form.nombre} onChange={(event) => setForm({ ...form, nombre: event.target.value })} /></label><label>Identificación<input maxLength={80} value={form.identificacion} onChange={(event) => setForm({ ...form, identificacion: event.target.value })} /></label><label>Teléfono<input maxLength={50} value={form.telefono} onChange={(event) => setForm({ ...form, telefono: event.target.value })} /></label><label>Dirección<textarea value={form.direccion} onChange={(event) => setForm({ ...form, direccion: event.target.value })} /></label><button className="primary" disabled={saving}>{saving ? 'Guardando…' : 'Guardar proveedor'}</button></form>{message && <p className="form-message admin-message">{message}</p>}</section><section className="panel list-panel"><div className="table-tools"><strong>Proveedores existentes</strong><span>{providers.length} registros</span></div><div className="table-wrap"><table><thead><tr><th>Nombre</th><th>Identificación</th><th>Teléfono</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{providers.length ? providers.map((provider) => <tr key={provider.id}><td>{provider.nombre}</td><td>{provider.identificacion || '—'}</td><td>{provider.telefono || '—'}</td><td><span className={`status ${provider.activo ? '' : 'status-inactive'}`}>{provider.activo ? 'Activo' : 'Inactivo'}</span></td><td><div className="admin-actions"><button className="edit-button" onClick={() => startEdit(provider)}><Pencil size={14} /> Editar</button><button className="edit-button" disabled={saving} onClick={() => void toggle(provider)}><Power size={14} /> {provider.activo ? 'Desactivar' : 'Activar'}</button></div></td></tr>) : <tr><td colSpan={5} className="empty-cell">No hay proveedores registrados.</td></tr>}</tbody></table></div></section></div></>;
}
