import { useEffect, useMemo, useState } from 'react';
import { Minus, Plus } from 'lucide-react';
import { api, formatMoney } from '../lib/api';
import { cacheList, getCachedList, queueMutation } from '../lib/offline-db';

type Row = Record<string, unknown>; type Line = { productoId: string; cantidad: number; valor: number };
const today = () => new Date().toISOString().slice(0, 10);
async function load(path: string, store?: Parameters<typeof getCachedList>[0]) { try { const rows = (await api<{ data: Row[] }>(path)).data; if (store) await cacheList(store, rows); return rows; } catch { return store ? getCachedList(store) : []; } }
export function TransactionPage({ kind }: { kind: 'compra' | 'venta' }) {
  const sale = kind === 'venta'; const [products, setProducts] = useState<Row[]>([]); const [partners, setPartners] = useState<Row[]>([]); const [contacts, setContacts] = useState<Row[]>([]); const [date, setDate] = useState(today()); const [partnerId, setPartnerId] = useState(''); const [contactId, setContactId] = useState(''); const [lines, setLines] = useState<Line[]>([{ productoId: '', cantidad: 1, valor: 0 }]); const [message, setMessage] = useState('');
  useEffect(() => { Promise.all([load('/catalogo/productos', 'productos'), load('/catalogo/socios', 'custodias'), load(sale ? '/catalogo/clientes' : '/catalogo/proveedores', sale ? 'clientes' : undefined)]).then(([p, s, c]) => { setProducts(p); setPartners(s); setContacts(c); }); }, [sale]);
  const custodyFor = (socioId: string) => ((partners.find((partner) => partner.id === socioId)?.custodias as Row[] | undefined) ?? []).find((custody) => custody.actividad === 'PRODUCTOS')?.id as string | undefined;
  const total = useMemo(() => lines.reduce((sum, line) => sum + line.cantidad * line.valor, 0), [lines]); const change = (index: number, update: Partial<Line>) => setLines((current) => current.map((line, i) => i === index ? { ...line, ...update } : line));
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage(''); if (!partnerId || !custodyFor(partnerId) || lines.some((line) => !line.productoId || line.cantidad < 1 || line.valor <= 0)) { setMessage('Completa socio, productos, cantidad y monto.'); return; }
    const payload = sale ? { clienteId: contactId || undefined, fecha: `${date}T12:00:00.000Z`, items: lines.map(({ productoId, cantidad, valor }) => ({ productoId, socioId: partnerId, custodiaId: custodyFor(partnerId), cantidad, precioUnitario: valor })) } : { proveedorId: contactId || undefined, socioId: partnerId, custodiaId: custodyFor(partnerId), fecha: date, items: lines.map(({ productoId, cantidad, valor }) => ({ productoId, cantidad, costoUnitario: valor })) };
    try { if (!navigator.onLine) { const id = crypto.randomUUID(); await queueMutation(sale ? 'ventas' : 'compras', sale ? 'venta' : 'compra', id, 'CREATE', payload); setMessage(`${sale ? 'Venta' : 'Compra'} guardada localmente; se sincronizará al recuperar conexión.`); } else { await api(`/${sale ? 'ventas' : 'compras'}`, { method: 'POST', body: JSON.stringify(payload) }); setMessage(`${sale ? 'Venta' : 'Compra'} confirmada correctamente.`); setLines([{ productoId: '', cantidad: 1, valor: 0 }]); } } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo guardar la operación.'); }
  }
  return <><section className="page-title"><div><p className="eyebrow">{sale ? 'VENTA DE CONTADO' : 'ENTRADA DE INVENTARIO'}</p><h2>{sale ? 'Registrar venta' : 'Registrar compra'}</h2><p>{sale ? 'El ingreso va a la custodia PRODUCTOS seleccionada; el stock siempre es general del negocio.' : 'El socio financia desde su custodia PRODUCTOS; las unidades entran al inventario general.'}</p></div></section><form className="transaction-form" onSubmit={submit}><section className="panel"><div className="form-grid"><label>Fecha<input type="date" value={date} onChange={(e) => setDate(e.target.value)} required /></label><label>{sale ? 'Cliente' : 'Proveedor'}<select value={contactId} onChange={(e) => setContactId(e.target.value)}><option value="">Sin especificar</option>{contacts.map((contact) => <option key={String(contact.id)} value={String(contact.id)}>{String(contact.nombre)}</option>)}</select></label><label>{sale ? 'Socio que recibe el ingreso' : 'Socio financiador'}<select value={partnerId} onChange={(e) => setPartnerId(e.target.value)} required><option value="">Seleccionar socio</option>{partners.map((partner) => <option key={String(partner.id)} value={String(partner.id)}>{String(partner.nombre)}</option>)}</select></label></div></section><section className="panel"><div className="panel-head"><div><h3>Productos</h3><p>Todos los productos pertenecen al inventario general de AR Inversiones.</p></div><button type="button" className="secondary" onClick={() => setLines((current) => [...current, { productoId: '', cantidad: 1, valor: 0 }])}><Plus size={16} /> Agregar línea</button></div>{lines.map((line, index) => <div className="line-item" key={index}><label>Producto<select value={line.productoId} onChange={(e) => change(index, { productoId: e.target.value })}><option value="">Seleccionar</option>{products.map((product) => <option key={String(product.id)} value={String(product.id)}>{String(product.nombre)}</option>)}</select></label><label>Cantidad<input type="number" min="1" value={line.cantidad} onChange={(e) => change(index, { cantidad: Number(e.target.value) })} /></label><label>{sale ? 'Precio unitario' : 'Costo final por unidad'}<input type="number" min="0.01" step="0.01" value={line.valor || ''} onChange={(e) => change(index, { valor: Number(e.target.value) })} /></label><strong>{formatMoney(line.cantidad * line.valor)}</strong>{lines.length > 1 && <button className="icon-button" type="button" aria-label="Quitar línea" onClick={() => setLines((current) => current.filter((_, i) => i !== index))}><Minus size={16} /></button>}</div>)}</section><section className="transaction-total"><div><span>Total</span><strong>{formatMoney(total)}</strong></div><button className="primary" type="submit">{navigator.onLine ? `Confirmar ${sale ? 'venta' : 'compra'}` : 'Guardar sin conexión'}</button></section>{message && <p className="form-message">{message}</p>}</form></>;
}
