import { describe, expect, it } from 'vitest';
import { addLoanMonth, filterLoans, loanSummary, paymentEstimate, type LoanRow } from './loan-management';
const loan = (changes: Partial<LoanRow>): LoanRow => ({ id: crypto.randomUUID(), cliente: 'Ana Pérez', socio: 'Rony', socio_id: 's', custodia_id: 'f', fondo_saldo: 1000, cliente_activo: true, capital_original: 1000, capital_pendiente: 1000, intereses_pendientes: 150, periodos_pendientes: 1, total_adeudado: 1150, tasa_mensual: 15, fecha_desembolso: '2026-01-01', fecha_proximo_pago: '2026-02-01', estado: 'ACTIVO', es_heredado: false, ...changes });
describe('préstamos', () => {
  it('suma meses preservando días válidos', () => { expect(addLoanMonth('2026-01-31')).toBe('2026-02-28'); expect(addLoanMonth('2028-01-31')).toBe('2028-02-29'); expect(addLoanMonth('2026-04-30')).toBe('2026-05-30'); expect(addLoanMonth('2026-12-31')).toBe('2027-01-31'); });
  it('calcula mínimo y distribución sin mezclar interés y capital', () => { expect(paymentEstimate(1000, 150, 150)).toMatchObject({ valid: true, interest: 150, capital: 0, remaining: 1000 }); expect(paymentEstimate(1000, 150, 450)).toMatchObject({ valid: true, interest: 150, capital: 300, remaining: 700 }); expect(paymentEstimate(1000, 150, 100).valid).toBe(false); expect(paymentEstimate(1000, 150, 1200).valid).toBe(false); });
  it('busca, filtra y prioriza vencidos', () => { const rows = [loan({ cliente: 'Carlos', estado: 'ACTIVO' }), loan({ cliente: 'Ána Pérez', estado: 'VENCIDO' }), loan({ cliente: 'Ana Pérez', estado: 'INCOBRABLE' })]; expect(filterLoans(rows, ' ana ', 'TODOS').map((row) => row.estado)).toEqual(['VENCIDO', 'INCOBRABLE']); expect(filterLoans(rows, '', 'ACTIVO')).toHaveLength(1); });
  it('separa cartera activa de capital incobrable', () => { expect(loanSummary([loan({ estado: 'VENCIDO' }), loan({ estado: 'INCOBRABLE', saldo_incobrable: 700 }), loan({ estado: 'RECUPERADO' })])).toMatchObject({ vencidos: 1, capitalActivo: 1000, incobrables: 1, capitalIncobrable: 700, recuperados: 1 }); });
});
