export type LoanState = 'ACTIVO' | 'VENCIDO' | 'PAGADO' | 'INCOBRABLE' | 'RECUPERADO' | 'ANULADO' | 'ELIMINADO';
export type LoanRow = { id: string; cliente: string; cliente_id: string; socio: string; socio_id: string; custodia_id: string; fondo_saldo: number | string; cliente_activo: boolean; capital_original: number | string; capital_pendiente: number | string; intereses_pendientes: number | string; periodos_pendientes: number | string; total_adeudado: number | string; tasa_mensual: number | string; fecha_desembolso: string | null; fecha_proximo_pago: string; estado: Exclude<LoanState, 'ELIMINADO'>; es_heredado: boolean; edicion_habilitada?: boolean; observaciones?: string | null; saldo_incobrable?: number | string | null; eliminado_at?: string | null; eliminado_por_nombre?: string | null; motivo_eliminacion?: string | null; estado_antes_eliminacion?: Exclude<LoanState, 'ELIMINADO'> | null };

const text = (value: unknown) => String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('es-HN').replace(/\s+/g, ' ').trim();
const statePriority: Record<LoanState, number> = { VENCIDO: 0, ACTIVO: 1, INCOBRABLE: 2, PAGADO: 3, RECUPERADO: 4, ANULADO: 5, ELIMINADO: 6 };
export const effectiveLoanState = (row: LoanRow): LoanState => row.eliminado_at ? 'ELIMINADO' : row.estado;
export function filterLoans(rows: LoanRow[], search: string, state: 'TODOS' | LoanState) { const term = text(search); return rows.filter((row) => { const effectiveState = effectiveLoanState(row); return (state === 'TODOS' ? effectiveState !== 'ELIMINADO' : effectiveState === state) && (!term || text(row.cliente).includes(term)); }).sort((a, b) => statePriority[effectiveLoanState(a)] - statePriority[effectiveLoanState(b)] || String(a.fecha_proximo_pago).localeCompare(String(b.fecha_proximo_pago)) || a.cliente.localeCompare(b.cliente, 'es-HN')); }
export function loanSummary(rows: LoanRow[]) { return rows.filter((row) => !row.eliminado_at).reduce((sum, row) => ({ activos: sum.activos + (row.estado === 'ACTIVO' ? 1 : 0), vencidos: sum.vencidos + (row.estado === 'VENCIDO' ? 1 : 0), capitalActivo: sum.capitalActivo + (['ACTIVO', 'VENCIDO'].includes(row.estado) ? Number(row.capital_pendiente) : 0), intereses: sum.intereses + (['ACTIVO', 'VENCIDO'].includes(row.estado) ? Number(row.intereses_pendientes) : 0), incobrables: sum.incobrables + (row.estado === 'INCOBRABLE' ? 1 : 0), capitalIncobrable: sum.capitalIncobrable + (row.estado === 'INCOBRABLE' ? Number(row.saldo_incobrable ?? 0) : 0), recuperados: sum.recuperados + (row.estado === 'RECUPERADO' ? 1 : 0) }), { activos: 0, vencidos: 0, capitalActivo: 0, intereses: 0, incobrables: 0, capitalIncobrable: 0, recuperados: 0 }); }
export function paymentEstimate(capital: number, interest: number, payment: number) { const cents = (value: number) => Math.round(value * 100); const due = cents(capital) + cents(interest); const paid = cents(payment); const interestPaid = Math.min(Math.max(paid, 0), cents(interest)); const capitalPaid = Math.max(0, Math.min(cents(capital), paid - cents(interest))); return { valid: paid > 0 && paid >= cents(interest) && paid <= due, minimum: cents(interest) / 100, maximum: due / 100, interest: interestPaid / 100, capital: capitalPaid / 100, remaining: (cents(capital) - capitalPaid) / 100 } as const; }
export function addLoanMonth(date: string) { const [year, month, day] = date.split('-').map(Number); const nextMonth = month === 12 ? 1 : month + 1; const nextYear = month === 12 ? year + 1 : year; const lastDay = new Date(Date.UTC(nextYear, nextMonth, 0)).getUTCDate(); return `${nextYear}-${String(nextMonth).padStart(2, '0')}-${String(Math.min(day, lastDay)).padStart(2, '0')}`; }
